
SYNC_CMD = "bundle exec octorule"
SYNC_ARGS =  "-o ecosyste-ms -t #{ENV.fetch("GITHUB_TOKEN")} --no-fork"
DRY_RUN = "-d"

task default: :sync

task :unsafe do
	DRY_RUN=""
end

task apply: [:unsafe, :sync]

task :sync, [:only] do |_task, args|

  options = {}
  opts = OptionParser.new
  opts.banner = "Usage: rake [options]"
  opts.on("-o", "--only ARG", String) { |pattern| options[:only] = "-n #{pattern}" }
  args = opts.order!(ARGV) {}
  opts.parse!(args)

  exec "#{SYNC_CMD} #{SYNC_ARGS} -s common.json #{DRY_RUN} #{options[:only]}"
end
